.travis.yml
See
- https://github.com/travis-ci/travis-ci/issues/9049
- https://travis-ci.org/ms-ati/docile/jobs/327830706
=> Remove jruby-9.1 from Travis due to failures

README.md, lib/docile.rb, spec/docile_spec.rb
This provides a new entry point called `dsl_eval_with_block_return`. It behaves exactly like `dsl_eval` but returns the output of calling the provided block, rather than returning the DSL object.
=> Add entry point that returns block output

lib/docile/execution.rb, lib/docile/fallback_context_proxy.rb, spec/docile_spec.rb
Previously, it turns out that this wasn't possible, which made
refactoring code that used Docile to extract common helper methods,
and re-use them in different blocks, a painful experience.
This change should make it possible to extract methods from blocks
into the context around the block, and have those extracted helper
methods still able to call methods on the DSL object.
=> Allow helper methods defined in the block's context to call DSL

lib/docile.rb, lib/docile/backtrace_filter.rb, lib/docile/fallback_context_proxy.rb, spec/docile_spec.rb
This is implementation of #35.
To do  this, remove entries including path to Docile's source file from `Exception#backtrace` and `Exception#backtrace_locations`.
=> Filter Docile's source files from backtrace

.travis.yml
Currently these Travis CI builds are failing to access Rubygems with following error:
Unable to download data from https://rubygems.org/ - hostname was not
match with the server certificate (https://rubygems.org/specs.4.8.gz)
This commit simply allows them to fail in CI without failing the entire build. As a
next step, we must either find a way to fix these test builds, or move forwards to
officially remove support for Ruby 1.8.
=> Allow travis failures of 1.8.7 and REE for now

.travis.yml
Oops, the intention had been to keep these tests running, but allow them to fail!
=> Restore testing 1.8.7 and ree in .travis.yml

.travis.yml
=> Update .travis.yml to remove 1.8.7 and REE

lib/docile.rb, lib/docile/chaining_fallback_context_proxy.rb, lib/docile/execution.rb, lib/docile/fallback_context_proxy.rb, spec/docile_spec.rb
Pull request for #56. Maybe @eregon could have a look at this?
One thing I am not sure about is if calling `module_function` for a method after calling `ruby2_keywords` works correctly.
=> Add ruby2_keywords to delegating methods

HISTORY.md, lib/docile/execution.rb, spec/docile_spec.rb
I ran into an issue invoking `Docile.dsl_eval_with_block_return` using a frozen object as the DSL
object, even though none of the code in the evaluated block attempts to mutate the frozen object:
```ruby
require 'docile'
class MyClass
def initialize
@something = proc { puts "Hello!" }
end
def evaluate(*args, &block)
Docile.dsl_eval_with_block_return(self, *args, &block)
end
def something
@something = Proc.new if block_given?
@something
end
def do_something
evaluate(&something)
end
end
MyClass.new.do_something
MyClass.new.tap { |mc| mc.something { puts "Goodbye!" } }.freeze.do_something
MyClass.new.freeze.do_something
```
```
$ ruby ./do_something.rb
Hello!
Goodbye!
Traceback (most recent call last):
9: from -e:1:in `<main>'
8: from -e:1:in `load'
7: from /path/to/do_something.rb:26:in …
```
=> Short-circuit to `dsl.instance_exec` when `dsl.equal?(block_context)`

.github/workflows/main.yml, Gemfile, README.md, docile.gemspec, spec/spec_helper.rb
Based on: https://github.com/ruby/setup-ruby
Re: #60
=> Add Github Actions CI configuration

.github/workflows/main.yml, spec/spec_helper.rb
Hi @ms-ati ,
This PR is to enable `bundler-cache` option of `setup-ruby` action.
We need to fix  `already initialized constant` warning reported when running RSpec.
https://github.com/ms-ati/docile/runs/2501978917?check_suite_focus=true#step:4:27
To fix this kind of warning, I've changed the condition to remove docile's files from `$LOAD_PATH`.
=> Use 'bundler-cache' option

.github/workflows/main.yml, Gemfile, spec/spec_helper.rb
Hi @ms-ati ,
I've introduce the codecov action to upload coverage reports instead of codecov gem.
This change is to prevent `ArgumentError` raised when uploading coverage reports by using codecov gem.
https://github.com/ms-ati/docile/runs/2511283031?check_suite_focus=true#step:5:101
=> Introduce Codecov action

docile.gemspec
Setting `changelog_uri` in `metadata` could help users find the changelog.
The link will be displayed on RubyGems.org.
It also makes the changelog discoverable by tools like https://github.com/envato/unwrappr.
Reference on RubyGems.org:
https://guides.rubygems.org/specification-reference/#metadata
=> Add metadata to gemspec

HISTORY.md
The CI configuration still runs against Ruby 2.5, whereas the release notes claim to drop support for it.
=> HISTORY.md: Ruby 2.5 is still supported in v1.4.0

spec/docile_spec.rb
Appears that TruffleRuby 22.0.0.2 reports RUBY_VERSION of 3.0.2,
but the observed behavior when we pass a hash final argument to
a method taking splat and double-splat arguments appears to be
the prior behavior of Ruby versions before 3.0.0.
=> Fix specs on TruffleRuby 22.0.0.2

.github/workflows/main.yml, Gemfile
We want to be careful to avoid accidentally bringing
in runtime dependencies to projects which use Docile.
In this PR, clarify explicitly that the CI-only dependency
on `simplecov-cobertura`, which is the formatt used by CodeCov,
is a **test** dependency, and not a runtime dependency.
Without this change, it may be possible that projects which use
Docile, when running in an environment with `CI=true`, would
accidentally bring in this test-only dependency, when that isn't
intended.
**Other changes**
- Remove unnecessary quoting of `'3.1'` in `.github/workflows/main.yml`
=> Move Gemfile CI-only dependencies to test group

.github/workflows/main.yml
Since we only run Rubocop on the latest MRI Ruby, dont
install the "checks" Gemfile group on other rubies in CI.
=> CI: exclude Gemfile 'checks' group except latest Ruby

spec/docile_spec.rb
ruby 3.3 changes error messages especially for NoMethodError: https://github.com/ruby/ruby/pull/6950
https://bugs.ruby-lang.org/issues/18285
Modify spec to support this new ruby 3.3 error messages.
Closes #105 .
=> TEST: support ruby 3.3 NoMethodError message

.github/workflows/main.yml, .rubocop.yml, docile.gemspec, lib/docile/chaining_fallback_context_proxy.rb, spec/docile_spec.rb, spec/spec_helper.rb
Add 3.2 and 3.3 to testing matrix. Drop truffleruby until such time as a user mentions it, as it sometimes fails and there’s no evidence it is being used.
=> Support Ruby 3.3

spec/docile_spec.rb
Removed a fix for TruffleRuby in specs to have them passed on the current TruffleRuby release (24.0).
=> Fix specs on TruffleRuby
